### ISSUE TITLE
Running agent without rack app

### ISSUE THREAD

**Issue by troex** [rails-autoscale/rails-autoscale-gems#40]
Hi,

We run sidekiq but our app now doesn't load rack middleware anymore so I need to run agent from sidekiq manually to report queue times, I've enabled with code above in in debug it sends data but I don't see updates in the autoscale app

```ruby
require 'rails_autoscale_agent/config'
require 'rails_autoscale_agent/store'
require 'rails_autoscale_agent/reporter'

RailsAutoscaleAgent::Config.logger = Logger.new($stdout)

RailsAutoscaleAgent::Reporter.start(
  RailsAutoscaleAgent::Config.instance,
  RailsAutoscaleAgent::Store.instance
)
```

Am I missing something or it's not designed to report only worker queues without web part?

**Comment by adamlogic** [comment]
> Am I missing something or it's not designed to report only worker queues without web part?

Well, technically it was designed only with Rack middleware in mind. As you've noticed both worker and web metrics are reported from the web process.

That said, I feel like what you've done here should work. Can you email me (adam@railsautoscale.com) with the specific logs you're seeing, and the name of your app so I can investigate what I'm seeing on my side?

**Comment by adamlogic** [comment]
Rack is no longer required in rails-autoscale-sidekiq 1.0.0
